### ISSUE TITLE
Can't see invitation

### ISSUE THREAD

**Issue by Owned67** [somini/Pixelvision2#110]
Can't see invitation

**Comment by Black4Blade** [comment]
What invitation do you mean? and where can you not see it?
I just don't really seem to be able to find this issue, so if you can just help me to point me on what is it you talking about?

**Comment by Owned67** [comment]
when you open friend, you don't see invitation tab at the end...

**Comment by mr-late** [comment]
Invite to what? A call, chat group, community group?

**Comment by Black4Blade** [comment]
I open the viewer on two screens one with the Skin one without, and I don't see any invite missing :(

Can you try to provide an image of it, so maybe it will help to understand what you are referring to?

**Comment by halbrd** [comment]
I think I might know what's going on here. Before the chat UI overhaul, the friends list window used to have an Add A Friend button at the bottom:

![image](https://user-images.githubusercontent.com/4065127/44304532-6a1abf00-a3a1-11e8-97b4-33f2b2529f2f.png)

Since the update, that button has been moved to the window header:

![image](https://user-images.githubusercontent.com/4065127/44304533-8159ac80-a3a1-11e8-8b49-ed1a9c6c7f8d.png)

Note that both of the screenshots above are with the default Steam skin. If this indeed the issue, then it's not anything to do with Pixelvision, this is just the new Steam interface layout.

**Comment by Owned67** [comment]
![invit](https://user-images.githubusercontent.com/1497809/44309067-ff797b80-a3c0-11e8-84b1-13e5e6c2532e.jpg)

**Comment by Black4Blade** [comment]
I see well we can't do anything with the skin for that now

Anyhow its there when you invite someone you can see it here:
![steamwebhelper_2018-08-19_16-54-24](https://user-images.githubusercontent.com/5269928/44309538-f2648880-a3d0-11e8-9adb-10c06001eda9.png)

That will show up after you invite someone or be invited

**Comment by Owned67** [comment]
Thanks :)
