### ISSUE TITLE
PixelVision² Updater Tool

### ISSUE THREAD

**Issue by Bluscream** [somini/Pixelvision2#87]
I know you probably heard of it already but i want to share it to the people that have more complicated ways to keep their skin up to date :D

https://github.com/Bluscream/PixelVision2-Updater

**Comment by Psycic101** [comment]
It's pretty cool. Major pity it's in C# which (realistically) limits it to Windows only. Hmmm perhaps a java implementation or similar would be better :? Maybe if I have some free time over the Christmas period.

**Comment by Bluscream** [comment]
Sure it's not very cross-platform xD But sure it shouldn't be hard to port it to another language :)

**Comment by somini** [comment]
I heard, and pinned the thread on the forums, but I'll merge #88 too.

There's Mono, c# is not the problem. Do you use WinForms, that's the windows specific part? 

Personally, even on Windows, i just use git directly. Since this is my repo, I even store my configs in the somini branches. 
I do understand that some people like gui buttons to push.

**Comment by somini** [comment]
I checked and it does use WinForms. 
https://github.com/Bluscream/PixelVision2-Updater/blob/master/PixelVision%20Updater.csproj

**Comment by Bluscream** [comment]
> Personally, even on Windows, i just use git directly. Since this is my repo, I even store my configs in the somini branches. 
> I do understand that some people like gui buttons to push.

Sadly i don't get what you're referencing to, there :o
But you can guess that i'm trying some stuff  :D 
![image](https://cloud.githubusercontent.com/assets/3318223/19943153/7c46576c-a136-11e6-880f-f4c201461743.png)
